source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts


future:      true
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     date
paginate_path: 'page:num'

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

kramdown:
  input: GFM


highlighter: pygments
excerpt_separator: "\n"

safe:        false
watch:       false    # deprecated
server:      false    # deprecated
port:        4000
baseurl:     /
url:         http://leequangang.github.com
lsi:         false

img_url: http://leequangang.github.com/images